name: Hello world

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Pessoa a ser cumprimentada'
#         required: true
#         default: 'Pedro Lacerda'
#       location:
#         description: 'Localização da pessoa no universo'
#         required: false
#         default: 'Planeta Terra'

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: env | sort
  
  job2:
    name: Segundo Job
    runs-on: windows-latest
    needs: job1
    
    steps:
      - name: Step 1
        run: "Get-ChildItem Env: | Sort-Object Name"
        
